apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crawler
  name: synergychat-crawler
  labels:
    app: synergychat-crawler
spec:
  replicas: 5
  selector:
    matchLabels:
      app: synergychat-crawler
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      volumes:
        - name: synergychat-crawler-volume
          persistentVolumeClaim:
            claimName: synergychat-crawler-pvc
      containers:
        - name: synergychat-crawler
          image: bootdotdev/synergychat-crawler:latest
          volumeMounts:
            - name: synergychat-crawler-volume
              mountPath: /persist
          envFrom:
            - configMapRef:
                name: synergychat-crawler-configmap
